from enum import Enum


class LanguageEnum(Enum):
    ARABIC_EG = "Arabic (Egypt)"
    ARABIC_MA = "Arabic (Morocco)"
    CHINESE_CN = "Chinese (China)"
    SPANISH_AR = "Spanish (Argentina)"
    SPANISH_ES = "Spanish (Spain)"
    SPANISH_MX = "Spanish (Mexico)"
    ENGLISH_UK = "English (UK)"
    ENGLISH_US = "English (US)"
    HINDI_IN = "Hindi (India)"
    ARABIC_SA = "Arabic (Saudi Arabia)"
    BENGALI_BD = "Bengali (Bangladesh)"
    PORTUGUESE_BR = "Portuguese (Brazil)"
    PORTUGUESE_PT = "Portuguese (Portugal)"
    RUSSIAN_RU = "Russian (Russia)"
    JAPANESE_JP = "Japanese (Japan)"
    PUNJABI_PK = "Punjabi (Pakistan)"
    GERMAN_DE = "German (Germany)"
    JAVANESE_ID = "Javanese (Indonesia)"
    WU_CN = "Wu (China)"
    MALAY_MY = "Malay (Malaysia)"
    TELUGU_IN = "Telugu (India)"
    VIETNAMESE_VN = "Vietnamese (Vietnam)"
    KOREAN_KR = "Korean (South Korea)"
    FRENCH_FR = "French (France)"
    MARATHI_IN = "Marathi (India)"
    TAMIL_IN = "Tamil (India)"
    URDU_PK = "Urdu (Pakistan)"
    TURKISH_TR = "Turkish (Turkey)"
    ITALIAN_IT = "Italian (Italy)"
    YUE_CN = "Yue (China)"
    THAI_TH = "Thai (Thailand)"
    GUJARATI_IN = "Gujarati (India)"
    JIN_CN = "Jin (China)"
    SOUTHERN_MIN_CN = "Southern Min (China)"
    PERSIAN_IR = "Persian (Iran)"
    POLISH_PL = "Polish (Poland)"
